stages:
- name: build
  steps:
  - publishImageConfig:
      dockerfilePath: ./debian/Dockerfile
      buildContext: ./debian/
      tag: atriarch-drawio:v1.0.${CICD_EXECUTION_SEQUENCE}
      pushRemote: true
      registry: docker.atriarch.systems
- name: Deploy
  steps:
  - applyYamlConfig:
      path: ./deployment.yaml
timeout: 10
notification: {}
